In [5]:
import numpy as np

In [6]:
#TESS ADCS Sensors
# two star trackers
# 4 cameras
# 10 coarse sun sensors

#Coarse star tracker specs
sigma_star = 6.0 #arcseconds
sigma_star = sigma_star * 1/3600.0 / 180.0 * np.pi #convert arcseconds to radians
cov_star = sigma_star**2 * np.eye(3)
print("Star tracker covariance matrix: ", cov_star)

#Camera star tracker specs
sigma_cam = 21 * 0.07 #arcsec ######
sigma_cam = sigma_cam * 1/3600.0 / 180.0 * np.pi #convert arcseconds to radians
cov_cam = sigma_cam**2 * np.eye(3)
print("Camera covariance matrix: ", cov_cam)


#Sun sensor specs [Do we want to include? No, It's not really used for pointing]


Star tracker covariance matrix:  [[8.46159499e-10 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.46159499e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.46159499e-10]]
Camera covariance matrix:  [[5.0790724e-11 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 5.0790724e-11 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 5.0790724e-11]]


In [10]:
# Simulate Noisy Measurements
#np.random.seed(41)  # for reproducibility
N = 10000  # number of samples

# Assume true measurement is zero vector for simplicity
true_measurement = np.zeros(3)

# Generate noisy measurements
star_measurements = true_measurement + np.random.multivariate_normal(np.zeros(3), cov_star, N)
cam_measurements = true_measurement + np.random.multivariate_normal(np.zeros(3), cov_cam, N)

# --- Verify Statistics ---
print("\nStar Tracker Sample Covariance:\n", np.cov(star_measurements, rowvar=False))
print("Camera Tracker Sample Covariance:\n", np.cov(cam_measurements, rowvar=False))

# Optional: check mean of the simulated measurements
print("\nStar Tracker Sample Mean:", np.mean(star_measurements, axis=0))
print("Camera Tracker Sample Mean:", np.mean(cam_measurements, axis=0))


Star Tracker Sample Covariance:
 [[8.70887016e-10 1.49251534e-11 8.96423009e-12]
 [1.49251534e-11 8.44935238e-10 1.05523153e-11]
 [8.96423009e-12 1.05523153e-11 8.39044490e-10]]
Camera Tracker Sample Covariance:
 [[ 5.00238798e-11 -5.20975043e-13 -8.29210643e-14]
 [-5.20975043e-13  5.03839169e-11 -5.03425660e-13]
 [-8.29210643e-14 -5.03425660e-13  5.13083883e-11]]

Star Tracker Sample Mean: [ 1.15017746e-07  3.20175383e-07 -3.91241384e-07]
Camera Tracker Sample Mean: [ 2.84503175e-08 -7.45926624e-08 -3.57580441e-08]


In [8]:
# #Noise generation?
# #Star tracker noise
# noise_star = np.random.normal(np.zeros(3), cov_star)
# star_true = np.array([0.5,0.5,0.5]) #Create arbitrary truth vector
# star_meas = star_true + noise_star
# star_meas = star_meas / np.linalg.norm(star_meas)

# #Camera noise
# noise_cam = np.random.normal(np.zeros(3), cov_cam)

# cam_true = np.array([0.5,0.5,0.5])
# cam_meas = cam_true + noise_cam
# cam_meas = cam_meas / np.linalg.norm(cam_meas)
