In [1]:
import numpy as np

In [ ]:
#TESS ADCS Sensors
# two star trackers
# 4 cameras
# 10 coarse sun sensors

#Coarse star tracker specs
sigma_star = 6.0 #arcseconds
sigma_star = sigma_star * 1/3600.0 / 180.0 * np.pi #convert arcseconds to radians
cov_star = sigma_star**2 * np.eye(3)
print("Star tracker covariance matrix: ", cov_star)

#Camera star tracker specs
sigma_cam = 21 * 0.07 #arcsec ######
sigma_cam = sigma_cam * 1/3600.0 / 180.0 * np.pi #convert arcseconds to radians
cov_cam = sigma_cam**2 * np.eye(3)
print("Camera covariance matrix: ", cov_cam)


#Sun sensor specs [Do we want to include? No, It's not really used for pointing]


Star tracker covariance matrix:  [[8.46159499e-10 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.46159499e-10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.46159499e-10]]
Camera covariance matrix:  [[5.0790724e-11 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 5.0790724e-11 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 5.0790724e-11]]


In [3]:
# #Noise generation?
# #Star tracker noise
# noise_star = np.random.normal(np.zeros(3), cov_star)
# star_true = np.array([0.5,0.5,0.5]) #Create arbitrary truth vector
# star_meas = star_true + noise_star
# star_meas = star_meas / np.linalg.norm(star_meas)

# #Camera noise
# noise_cam = np.random.normal(np.zeros(3), cov_cam)

# cam_true = np.array([0.5,0.5,0.5])
# cam_meas = cam_true + noise_cam
# cam_meas = cam_meas / np.linalg.norm(cam_meas)
